### ISSUE TITLE
Instructions too generic 

### ISSUE THREAD

**Issue by Madis0** [monsiu/Custom-RR#5]
The installation instructions are too generic and expect some know-how already. Please try to include more device-specific ones, especially how to unlock the bootloader and whether a device even can use custom recoveries to do things, as many new ones can't.

**Comment by monsiu** [comment]
Thanks Madis0.

I will fix this and add more clear instructions to help the people new to rooting.

**Comment by monsiu** [comment]
Updated. Tell me what you think.
