### ISSUE TITLE
GSIs

### ISSUE THREAD

**Issue by Madis0** [monsiu/Custom-RR#6]
You say you want to support every obscure device, so why not list the "generic ROMs" aka GSIs too?

**Comment by monsiu** [comment]
Thank you for the suggestion. 

GSI's would be a great addition since i am a huge fan of project trebble devices so be sure that i will add this thanks to you.

I will also look to provide support for every obscure device and i will also ensure this in a new release. 

Stay Tuned For Great Things!

**Comment by monsiu** [comment]
@Madis0 added this in the release :)
